from setuptools import setup, find_packages

setup(
    name="papermind",
    version="1.0.0",
    author="Devarshi Dixit",
    description="PaperMind — Multilingual Document Intelligence System using RAG",
    url="https://github.com/dixitdevarshi/PaperMind",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.10",
    install_requires=[
        "anthropic==0.29.0",
        "langchain==0.2.6",
        "langchain-community==0.2.6",
        "langchain-core==0.2.10",
        "pymupdf==1.24.5",
        "pillow==10.3.0",
        "sentence-transformers==3.0.1",
        "torch==2.3.1",
        "transformers==4.41.2",
        "chromadb==0.5.3",
        "ragas==0.1.10",
        "datasets==2.20.0",
        "fastapi==0.111.0",
        "uvicorn[standard]==0.30.1",
        "python-multipart==0.0.9",
        "httpx==0.27.0",
        "pydantic==2.7.4",
        "python-dotenv==1.0.1",
        "tqdm==4.66.4",
        "numpy==1.26.4",
        "pandas==2.2.2",
        "scipy==1.13.1",
    ],
    classifiers=[
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)